language: node_js

node_js:
  - "4"

notifications:
  email: false

script:
  - gulp build
  - gulp test

cache: yarn

addons:
  code_climate:
    repo_token: a1ddc98a1e790ae75102887578b5b3e1a516056a5ce699a2e72a01d384131cba

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info